"""empty message

Revision ID: 083d58ad08a9
Revises: 8c2960c2ebe6
Create Date: 2020-07-17 09:32:27.512345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083d58ad08a9'
down_revision = '8c2960c2ebe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_pic', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic')
    # ### end Alembic commands ###
