"""empty message

Revision ID: 0b478c8a23a1
Revises: 083d58ad08a9
Create Date: 2020-07-20 03:07:49.355539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b478c8a23a1'
down_revision = '083d58ad08a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('countryVisited', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'countryVisited')
    # ### end Alembic commands ###
