"""empty message

Revision ID: 1d310981707e
Revises: 5e9b2a58bfcd
Create Date: 2020-06-24 10:31:33.185956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d310981707e'
down_revision = '5e9b2a58bfcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'doctor', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor', type_='foreignkey')
    op.drop_column('doctor', 'role_id')
    # ### end Alembic commands ###
