"""empty message

Revision ID: 3b44ec094e1f
Revises: f0b03361474f
Create Date: 2020-04-18 20:27:28.149035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b44ec094e1f'
down_revision = 'f0b03361474f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sign_up_method', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sign_up_method')
    # ### end Alembic commands ###
