"""empty message

Revision ID: 8a7168e5fb1d
Revises: 8a9a8912f748
Create Date: 2020-06-17 17:34:44.378730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7168e5fb1d'
down_revision = '8a9a8912f748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('doc_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'doc_id')
    # ### end Alembic commands ###
