"""empty message

Revision ID: f0b03361474f
Revises: ca1a4373782e
Create Date: 2020-04-18 19:27:13.366055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b03361474f'
down_revision = 'ca1a4373782e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specifics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cough_degree', sa.String(length=50), nullable=True),
    sa.Column('fever_degree', sa.String(length=50), nullable=True),
    sa.Column('fatigue_degree', sa.String(length=50), nullable=True),
    sa.Column('other_degree', sa.String(length=50), nullable=True),
    sa.Column('symptom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specifics')
    # ### end Alembic commands ###
